version: '3.8'
services:
  app:
    build: .
    environment:
      DB_URL: jdbc:mysql://mysqlserver:3306/demo
      DB_USER: developer
      DB_PASS: password
    ports:
      - "8080:8080"
  mysqlserver:
    image: 'mysql:latest'
    volumes:
      - db_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: developer
      MYSQL_PASSWORD: password
      MYSQL_HOST: '%'
    ports:
      - "3306:3306"
volumes:
  db_mysql:
