apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: jwt-gateway
  namespace: default
  labels:
    app: gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: http
      port: 97
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
---
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: req-authn-for-all
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: gateway
  jwtRules:
    - issuer: "https://fungover.org/auth"
      jwksUri: https://fungover.org/auth/.well-known/jwks.json
#      outputClaimToHeaders:
#        - header: "x-jwt-claim-sub"
#          claim: "sub"
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: bookinfo
  namespace: default
spec:
  parentRefs:
    - name: jwt-gateway
  rules:
    - matches:
        - path:
            type: Exact
            value: /
      backendRefs:
        - name: spring
          port: 8080
    - matches:
        - path:
            type: PathPrefix
            value: /showheaders
      backendRefs:
        - name: spring
          port: 8080
