apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: jwt-gateway
  namespace: default
  labels:
    app: gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: virtualservice
  namespace: default
spec:
  hosts:
    - "*"
  gateways:
    - jwt-gateway
  http:
    - name: auth
      match:
      - uri:
         prefix: /showheaders
      rewrite:
        uri: /
      route:
        - destination:
            host: backend
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: "jwt-example"
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  jwtRules:
    - issuer: "https://fungover.org/auth"
      jwksUri: https://fungover.org/auth/.well-known/jwks.json
      outputClaimToHeaders:
        - header: "userID"
          claim: "sub"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt-for-all
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
