apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-test   #It's important that the name of the ConfigMap matches the name of the application as specified in our “application.properties” file.
  namespace: default
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  application.properties: |-
    bean.message=Hello Martin!
    bean.showheaders=false
